"""
gradio_loader.py
================
A LlamaIndex-compatible CustomLLM that sends inference requests to a remote
Gradio server hosting Gemma (or any causal LM) via its REST API.

The remote server exposes two endpoints:
  POST /api/predict   → non-streaming, returns full text   (used by LlamaIndex)
  POST /queue/join    → streaming SSE                      (not used here)

Usage:
    from llm_loaders.gradio_loader import GradioLoader
    loader = GradioLoader(base_url="http://192.168.1.x:7860", ...)
    llm    = loader.get_llm()
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Generator, Optional, Sequence

import requests
from llama_index.core.llms import (
    CompletionResponse,
    CompletionResponseGen,
    CustomLLM,
    LLMMetadata,
)
from llama_index.core.llms.callbacks import llm_completion_callback

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_prompt(messages: list[dict]) -> str:
    """
    Convert a list of {"role": ..., "content": ...} dicts into a single
    prompt string using the Gemma instruct template.
    We do this client-side so the server receives a plain string.
    """
    parts = []
    for m in messages:
        role = m["role"]
        content = m["content"]
        if role == "user":
            parts.append(f"<start_of_turn>user\n{content}<end_of_turn>")
        elif role == "assistant":
            parts.append(f"<start_of_turn>model\n{content}<end_of_turn>")
        elif role == "system":
            # Gemma has no dedicated system token; prepend as a user turn
            parts.append(f"<start_of_turn>user\n[SYSTEM]: {content}<end_of_turn>")
    parts.append("<start_of_turn>model\n")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# GradioLLM — the LlamaIndex CustomLLM wrapper
# ---------------------------------------------------------------------------

class GradioLLM(CustomLLM):
    """
    Thin wrapper around a remote Gradio /api/predict endpoint.
    Works for any gr.Interface(fn=generate, inputs='text', outputs='text').
    """

    base_url: str
    context_window: int
    max_new_tokens: int
    temperature: float
    timeout: float

    @property
    def metadata(self) -> LLMMetadata:
        return LLMMetadata(
            context_window=self.context_window,
            num_output=self.max_new_tokens,
            model_name="gemma-4-e4b-it (remote-gradio)",
        )

    def _call_api(self, prompt: str) -> str:
        """Call the Gradio server using the official gradio_client.
        
        This handles all the messy HTTP routing automatically, regardless
        of whether the remote server is running Gradio 3 or 4.
        """
        try:
            from gradio_client import Client
        except ImportError:
            raise ImportError(
                "Please run `pip install gradio_client` to use the Gradio backend."
            )

        try:
            # Create client (automatically fetches the API spec from the server)
            client = Client(self.base_url)
            # Send the prompt to the default API endpoint
            result = client.predict(prompt)
            return str(result)
            
        except Exception as e:
            raise ConnectionError(
                f"[GradioLLM] Failed to call Gradio server at {self.base_url}.\n"
                f"Error: {str(e)}"
            ) from e

    # ------------------------------------------------------------------
    # LlamaIndex interface
    # ------------------------------------------------------------------

    @llm_completion_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        text = self._call_api(prompt)
        return CompletionResponse(text=text)

    @llm_completion_callback()
    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        """
        Uses gradio_client.submit() to open an SSE stream and yield 
        tokens in real-time as they are generated by the server.
        """
        try:
            from gradio_client import Client
        except ImportError:
            raise ImportError("Please run `pip install gradio_client`")

        client = Client(self.base_url)
        # .submit() creates an asynchronous Job object that we can iterate over
        job = client.submit(prompt)

        def _gen() -> Generator[CompletionResponse, None, None]:
            previous_text = ""
            try:
                for text in job:
                    # Gradio yields the cumulative string at each step.
                    # LlamaIndex wants the 'delta' (new characters only).
                    delta = text[len(previous_text):]
                    previous_text = text
                    yield CompletionResponse(text=text, delta=delta)
            except Exception as e:
                raise ConnectionError(f"[GradioLLM] Stream failed: {e}")

        return _gen()


# ---------------------------------------------------------------------------
# GradioLoader — mirrors the pattern of OllamaLoader / QuantizedLocalLLM
# ---------------------------------------------------------------------------

class GradioLoader:
    """
    Factory that creates a GradioLLM instance wired to the remote server.

    The server URL is resolved in this priority order:
      1. GRADIO_LLM_URL environment variable  ← set this each session
      2. base_url argument (from config.yaml)

    Workflow each time the JupyterLab server restarts:
      PowerShell : $env:GRADIO_LLM_URL = "https://xxxx.gradio.live"
      bash/zsh   : export GRADIO_LLM_URL="https://xxxx.gradio.live"

    Args:
        base_url        : Fallback URL from config.yaml (used when env var absent)
        context_window  : Context window to advertise to LlamaIndex (tokens)
        max_new_tokens  : Max tokens to generate per call
        temperature     : Sampling temperature (informational — controlled server-side)
        timeout         : HTTP request timeout in seconds
    """

    def __init__(
        self,
        base_url: str,
        context_window: int = 8192,
        max_new_tokens: int = 1024,
        temperature: float = 0.2,
        timeout: float = 120.0,
    ) -> None:
        # Env var takes priority — lets you paste the new gradio.live URL
        # into your shell each session without editing any file.
        env_url = os.environ.get("GRADIO_LLM_URL", "").strip()
        self.base_url = env_url if env_url else base_url
        self.context_window = context_window
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.timeout = timeout

        if env_url:
            logger.info(f"[GradioLoader] Using URL from GRADIO_LLM_URL env var → {self.base_url}")
        else:
            logger.info(f"[GradioLoader] Using URL from config.yaml → {self.base_url}")

    def get_llm(self) -> GradioLLM:
        logger.info(f"[GradioLoader] Connecting to remote Gradio server → {self.base_url}")
        return GradioLLM(
            base_url=self.base_url,
            context_window=self.context_window,
            max_new_tokens=self.max_new_tokens,
            temperature=self.temperature,
            timeout=self.timeout,
        )
